// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ybduozvbycnwwlrvjiim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliZHVvenZieWNud3dscnZqaWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODM1NzEsImV4cCI6MjA3MDA1OTU3MX0.P3yXIdDo9JjYmSwU3MiR1xGu8kqA04W8p5Zu2Il2n-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);